const ACTION = {
    ADD_MOVIE_TO_MOVIE_DATA : "ADD_MOVIE_TO_MOVIE_DATA",
    CLEAR_MOVIE_DATA : "CLEAR_MOVIE_DATA",
    ADD_MOVIE_BANNER_DATA : "ADD_MOVIE_BANNER_DATA",
    ADD_MOVIE_TO_MOVIE_DATA_GENRE : "ADD_MOVIE_TO_MOVIE_DATA_GENRE",
    SET_SEARCH : "SET_SEARCH",
    SET_DISPLAY_MESSAGE:"SET_DISPLAY_MESSAGE"
}

export default ACTION;
